import { MAP_VIEWS } from '../mapConfig.js'

/**
 * Data-driven country registry.
 *
 * To add a new country, add a single entry here.  All map logic
 * (enrichment, styling, events, tooltips, stats panel) reads from
 * this registry instead of hard-coding per-country branches.
 */
export const COUNTRIES = {
  uk: {
    key: 'uk',
    idPrefix: 'uk',
    displayTitle: 'GREAT BRITAIN',
    statsLabel: 'Total GB Output',
    featureIdProp: 'ID',
    featureIdFallbackProp: null,
    displayNameProp: 'Area',
    displaySubProp: 'DNO_Full',
    displaySubFallback: null,
    displayIdProp: 'ID',
    displayIdFallback: null,
    dataSource: 'Sheffield Solar (PV_Live)',
    hasMicroData: true,
    mapView: MAP_VIEWS.UK,
  },

  france: {
    key: 'france',
    idPrefix: 'fr',
    displayTitle: 'FRANCE',
    statsLabel: 'Total France Output',
    featureIdProp: 'code',
    featureIdFallbackProp: null,
    displayNameProp: 'nom',
    displaySubProp: null,
    displaySubFallback: 'France Region',
    displayIdProp: 'code',
    displayIdFallback: null,
    dataSource: 'RTE (éCO2mix)',
    hasMicroData: true,
    mapView: MAP_VIEWS.FRANCE,
  },

  germany: {
    key: 'germany',
    idPrefix: 'de',
    displayTitle: 'GERMANY',
    statsLabel: 'Total Germany Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Germany (State)',
    displayIdProp: 'id',
    displayIdFallback: 'DE',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.GERMANY,
  },

    spain: {
    key: 'spain',
    idPrefix: 'es',
    displayTitle: 'SPAIN',
    statsLabel: 'Total Spain Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Spain',
    displayIdProp: 'id',
    displayIdFallback: 'ES',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.SPAIN,
  },

  netherlands: {
    key: 'nl',
    idPrefix: 'nl',
    displayTitle: 'NETHERLANDS',
    statsLabel: 'Total Netherlands Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Netherlands',
    displayIdProp: 'id',
    displayIdFallback: 'NL',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.NETHERLANDS,
  },

  austria: {
    key: 'at',
    idPrefix: 'at',
    displayTitle: 'AUSTRIA',
    statsLabel: 'Total Austria Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Austria',
    displayIdProp: 'id',
    displayIdFallback: 'AT',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.AUSTRIA,
  },

  switzerland: {
    key: 'ch',
    idPrefix: 'ch',
    displayTitle: 'SWITZERLAND',
    statsLabel: 'Total Switzerland Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Switzerland',
    displayIdProp: 'id',
    displayIdFallback: 'CH',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.SWITZERLAND,
  },

  poland: {
    key: 'pl',
    idPrefix: 'pl',
    displayTitle: 'POLAND',
    statsLabel: 'Total Poland Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Poland',
    displayIdProp: 'id',
    displayIdFallback: 'PL',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.POLAND,
  },

  czechia: {
    key: 'cz',
    idPrefix: 'cz',
    displayTitle: 'CZECHIA',
    statsLabel: 'Total Czechia Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Czechia',
    displayIdProp: 'id',
    displayIdFallback: 'CZ',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.CZECHIA,
  },

  denmark: {
    key: 'denmark',
    idPrefix: 'dk',
    displayTitle: 'DENMARK',
    statsLabel: 'Total Denmark Output',
    featureIdProp: 'id',
    featureIdFallbackProp: 'name',
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Bidding Zone',
    displayIdProp: 'id',
    displayIdFallback: 'DK',
    dataSource: 'Energinet',
    hasMicroData: true,
    mapView: MAP_VIEWS.DENMARK,
  },

  belgium: {
    key: 'belgium',
    idPrefix: 'be',
    displayTitle: 'BELGIUM',
    statsLabel: 'Total Belgium Output',
    featureIdProp: 'name',
    featureIdFallbackProp: null,
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Region',
    displayIdProp: 'id',
    displayIdFallback: 'BE',
    dataSource: 'Elia',
    hasMicroData: true,
    mapView: MAP_VIEWS.BELGIUM,
  },

  portugal: {
    key: 'portugal',
    idPrefix: 'pt',
    displayTitle: 'PORTUGAL',
    statsLabel: 'Total Portugal Output',
    featureIdProp: 'name',
    featureIdFallbackProp: null,
    displayNameProp: 'name',
    displaySubProp: null,
    displaySubFallback: 'Portugal',
    displayIdProp: 'id',
    displayIdFallback: 'PT',
    dataSource: 'Fraunhofer ISE (Energy-Charts)',
    hasMicroData: false,
    mapView: MAP_VIEWS.PORTUGAL,
  },

  italy: {
    key: 'italy',
    idPrefix: 'it',
    displayTitle: 'ITALY',
    statsLabel: 'Total Italy Output',
    featureIdProp: 'bidding_zone',
    featureIdFallbackProp: null,
    displayNameProp: 'zone_name',
    displaySubProp: 'reg_name',
    displaySubFallback: 'Italy',
    displayIdProp: 'bidding_zone',
    displayIdFallback: 'IT',
    dataSource: 'ENTSO-E',
    hasMicroData: true,
    mapView: MAP_VIEWS.ITALY,
  },

  ireland: {
    key: 'ireland',
    idPrefix: 'ie',
    displayTitle: 'IRELAND',
    statsLabel: 'Total Ireland Output',
    featureIdProp: 'NUTS_ID',
    featureIdFallbackProp: 'CNTR_CODE',
    displayNameProp: 'NAME_LATN',
    displaySubProp: null,
    displaySubFallback: 'Ireland',
    displayIdProp: 'NUTS_ID',
    displayIdFallback: 'IE',
    dataSource: 'ENTSO-E',
    hasMicroData: false,
    mapView: MAP_VIEWS.IRELAND || { center: [-8.0, 53.0], zoom: 6.0 },
    disabledHoverMessage: 'No live solar generation data available',
  },

  northern_ireland: {
    key: 'northern_ireland',
    idPrefix: 'ni',
    displayTitle: 'NORTHERN IRELAND',
    statsLabel: 'Total NI Output',
    featureIdProp: 'NUTS_ID',
    featureIdFallbackProp: 'CNTR_CODE',
    displayNameProp: 'NAME_LATN',
    displaySubProp: null,
    displaySubFallback: 'Northern Ireland',
    displayIdProp: 'NUTS_ID',
    displayIdFallback: 'UKN',
    dataSource: 'ENTSO-E',
    hasMicroData: false,
    mapView: MAP_VIEWS.NORTHERN_IRELAND || { center: [-6.5, 54.6], zoom: 6.5 },
    disabledHoverMessage: 'No live solar generation data available',
  },

  sweden: {
    key: 'sweden',
    idPrefix: 'se',
    displayTitle: 'SWEDEN',
    statsLabel: 'Total Sweden Output',
    featureIdProp: 'bidding_zone',
    featureIdFallbackProp: null,
    displayNameProp: 'NUTS_NAME',
    displaySubProp: 'bidding_zone',
    displaySubFallback: 'Sweden',
    displayIdProp: 'bidding_zone',
    displayIdFallback: 'SE',
    dataSource: 'ENTSO-E',
    hasMicroData: true,
    mapView: MAP_VIEWS.SWEDEN,
  },

  norway: {
    key: 'norway',
    idPrefix: 'no',
    displayTitle: 'NORWAY',
    statsLabel: 'Total Norway Output',
    featureIdProp: 'bidding_zone',
    featureIdFallbackProp: null,
    displayNameProp: 'NAME_LATN',
    displaySubProp: 'bidding_zone',
    displaySubFallback: 'Norway',
    displayIdProp: 'bidding_zone',
    displayIdFallback: 'NO',
    dataSource: 'ENTSO-E',
    hasMicroData: true,
    mapView: MAP_VIEWS.NORWAY,
  },
}

/** Ordered array of country keys (stable iteration order). */
export const COUNTRY_KEYS = Object.keys(COUNTRIES)
